Use pre-commit for Git hook scripts
[`pre-commit`](https://pre-commit.com/) allows installing Git hooks from
remote repositories and committing your hooks (or their configuration)
in your Git repo.

diff --git a/.config/git/template/hooks/post-commit b/.config/git/template/hooks/post-commit
--- a/.config/git/template/hooks/post-commit
+++ b/.config/git/template/hooks/post-commit
@@ -1,3 +1,24 @@
 #!/usr/bin/env bash
-. "$(dirname "${BASH_SOURCE[0]}")/common.bash"
-"${GIT_DIR}/hooks/ctags" >/dev/null 2>&1 &
+# File generated by pre-commit: https://pre-commit.com
+# ID: 138fd403232d2ddd5efb44317e38bf03
+
+# start templated
+INSTALL_PYTHON=/opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
+ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=post-commit)
+# end templated
+
+HERE="$(cd "$(dirname "$0")" && pwd)"
+ARGS+=(--hook-dir "$HERE" -- "$@")
+
+filter_out_passed_skipped () {
+    grep -E -v '(Passed|Skipped)('$'\E''\[m)?$' >/dev/tty; rv=$?; [ $rv -le 1 ] && return 0; return $rv
+}
+
+if [ -x "$INSTALL_PYTHON" ]; then
+    "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}" | filter_out_passed_skipped
+elif command -v pre-commit > /dev/null; then
+    pre-commit "${ARGS[@]}" | filter_out_passed_skipped
+else
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
+    exit 1
+fi
